[package]
name = "screenpipe-core"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
serde_json = "1.0"
which = "6.0.1"
log = "0.4.17"
anyhow = "1.0.86"
candle = { workspace = true, optional = true }
candle-nn = { workspace = true, optional = true }
candle-transformers = { workspace = true, optional = true }
tokenizers = { workspace = true, optional = true }
hf-hub = { workspace = true, features = ["tokio"], optional = true }

# pipes
reqwest = { workspace = true }
tokio = { workspace = true }

deno_core = { version = "0.311.0", optional = true }
deno_ast = { version = "0.38.2", features = ["transpiling"], optional = true }
# Security
regex = { version = "1.10.6", features = ["std"], optional = true }
lazy_static = { version = "1.4.0", optional = true }
tempfile = "3.3.0"
url = "2.4.0"

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

dirs = "5.0.0"
lettre = "0.11.0"
[features]
default = ["pipes", "security"]
llm = ["candle", "candle-nn", "candle-transformers", "tokenizers", "hf-hub"]
pipes = ["dep:deno_core", "dep:deno_ast"]
security = ["dep:regex", "dep:lazy_static"]
metal = ["candle/metal", "candle-nn/metal", "candle-transformers/metal"]
cuda = ["candle/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
mkl = ["candle/mkl", "candle-nn/mkl", "candle-transformers/mkl"]

[build-dependencies]
# Move this under the same feature flag
deno_core = { version = "0.311.0", optional = true }
