version: "3.7"
services:
  thumbor:
    image: mvhirsch/thumbor:latest
    container_name: thumbor
    restart: always
    ports:
      - 2873:8888
    environment:
      - HTTP_LOADER_FORWARD_HEADERS_WHITELIST=["Referer"]
      - AUTO_WEBP=True
      - HTTP_LOADER_CONNECT_TIMEOUT=10
      - HTTP_LOADER_REQUEST_TIMEOUT=30
      - RESULT_STORAGE_STORES_UNSAFE=True
    volumes:
      - thumbor:/usr/local/thumbor/result_storage

volumes:
  thumbor:
